export const FIRST_PAGE_REVIEW_COMMENTS: Record<string, readonly string[]> = {
  "vestido-aurora-marfim": [
    "Usei no almoço de noivado da minha irmã e me senti muito elegante. O marfim é delicado e não ficou transparente.",
    "Tenho 1,62 m e o comprimento com salto baixo ficou perfeito. A cintura desenhou o corpo sem apertar.",
    "Comprei com receio de o tecido parecer fino, mas ele tem um peso ótimo e a saia se movimenta lindamente.",
    "Foi minha escolha para um batizado de manhã. Ficou sofisticado na medida, sem parecer roupa de festa demais.",
    "Segui as medidas da tabela e o M assentou direitinho no busto e na cintura. Não precisei fazer nenhum ajuste.",
    "O acabamento por dentro me surpreendeu, principalmente na barra. É uma peça clara que passa muita segurança ao vestir.",
    "Chegou dobrado com cuidado e quase não amassou. Coloquei um cinto fino e o look ficou um charme.",
    "Na luz natural a cor é um marfim muito bonito, nada amarelado. Com acessórios dourados ficou maravilhoso.",
    "Dá para andar e sentar com conforto porque a saia tem bastante movimento. Passei horas com ele e não incomodou.",
    "É daqueles vestidos que resolvem a produção sozinhos. Recebi elogio até de quem normalmente nem comenta minha roupa.",
  ],
  "vestido-aurora-cafe": [
    "O tom café é ainda mais rico pessoalmente e combinou muito com meu subtom quente. Fiquei apaixonada assim que vesti.",
    "Usei com sandália bege durante o dia e depois troquei por salto preto à noite. O vestido funcionou super bem nas duas ocasiões.",
    "A saia abre na medida certa quando a gente anda e deixa o visual feminino sem exagero. Caimento muito bonito.",
    "Tenho bastante busto e sempre fico insegura comprando vestido online, mas o G acomodou bem e não repuxou.",
    "A cintura ficou exatamente no lugar, algo raro para mim que sou mais baixinha. Não precisei encurtar nem ajustar as laterais.",
    "Levei numa viagem e foi a peça que mais usei. O tecido desamassa fácil e a cor não mostra qualquer marquinha.",
    "Marrom costuma ser difícil de acertar, porém esse café é profundo e chique. Ficou lindo com bolsa caramelo.",
    "Gostei porque é arrumado, mas continua confortável para um jantar longo. A modelagem não prende os movimentos.",
    "Minha mãe pediu o link depois que me viu usando. Ao vivo ele tem uma presença que as fotos não conseguem mostrar totalmente.",
    "Vesti para trabalhar com blazer e depois saí sem ele. É versátil de verdade e já virou um dos favoritos do armário.",
  ],
  "vestido-monument-noir": [
    "Escolhi para uma formatura e foi a roupa mais elogiada da noite. O detalhe no ombro fica escultural sem pesar no visual.",
    "O contraste do preto com o marfim é muito elegante ao vivo. Parece vestido de atelier e fotografa maravilhosamente bem.",
    "Tenho 1,70 m e usei com salto de 7 cm; a barra ficou no ponto. A parte assimétrica se mantém bonita mesmo em movimento.",
    "Fiquei com medo de o volume do ombro aumentar demais, mas ele equilibra a silhueta e deixa a postura linda.",
    "O tecido tem estrutura onde precisa e fluidez na saia. Dancei a festa inteira sem ficar ajeitando o vestido.",
    "Segui a tabela e escolhi o G por causa do quadril. Serviu bem na cintura e não marcou a lingerie.",
    "É uma peça marcante, mas muito refinada. Usei brincos pequenos e ainda assim a produção ficou completa.",
    "Chegou impecável na embalagem, sem nenhum fio solto. O acabamento do ombro foi o que mais me impressionou.",
    "Ao caminhar, a saia cria um efeito lindo e o recorte permanece alinhado. Me senti segura durante todo o evento.",
    "Comprei para um casamento black tie e acertou em cheio. Tem personalidade e não se parece com os vestidos comuns de festa.",
  ],
  "colete-alvorada": [
    "Usei fechado como blusa com uma calça de cintura alta e ficou muito elegante. Os botões dão um acabamento delicado.",
    "A alfaiataria tem estrutura, mas não é dura. O colete acompanha o corpo e não forma volume na lateral.",
    "O off-white é bonito e uniforme, sem aquele aspecto transparente de tecido barato. Dá para usar tranquilamente sem blazer.",
    "Tenho ombros largos e o G vestiu super bem nas cavas. Ficou alinhado e não apertou quando movimentei os braços.",
    "Combinei com jeans reto e mocassim para o trabalho. Em segundos o look básico ficou muito mais arrumado.",
    "A barra assimétrica faz diferença de verdade e alonga visualmente. Achei a modelagem moderna e feminina.",
    "Veio com as costuras bem limpas e os botões firmes. É o tipo de peça que parece mais cara do que custou.",
    "Aberto sobre uma regata ficou leve para o calor. Já estou pensando em várias combinações para meia-estação.",
    "Sou baixinha e gostei da proporção, porque não encurtou o tronco. O P ficou certinho seguindo a tabela.",
    "Com saia midi ficou romântico; com calça preta, bem profissional. Poucas peças do meu armário rendem tantos looks diferentes.",
  ],
  "vestido-satin-espresso": [
    "O cetim tem brilho sofisticado, não aquele efeito plástico. À noite o tom espresso fica simplesmente maravilhoso.",
    "Usei em um casamento e o decote caiu muito bem, sem ficar abrindo. Ajustei as alças e passei a festa toda confortável.",
    "A saia desliza no corpo em vez de grudar. Mesmo sentada, o tecido não marcou a região da barriga.",
    "Tenho seios pequenos e o decote degagê deu um volume bonito e natural. A modelagem ficou super feminina em mim.",
    "O marrom profundo foge do preto básico, mas continua fácil de combinar. Usei acessórios dourados e ficou luxuoso.",
    "Chegou antes do evento e veio muito bem protegido. Bastou vapor leve para o tecido ficar lisinho.",
    "Escolhi o tamanho pelo quadril e deu certo também na cintura. O vestido acompanha as curvas sem ficar justo demais.",
    "Na pista ele se movimenta de um jeito lindo e não pesa. Recebi várias perguntas sobre onde tinha comprado.",
    "As alças reguláveis salvaram o ajuste para mim, porque tenho o tronco curto. O decote permaneceu no lugar a noite inteira.",
    "É sensual com elegância, exatamente o que eu procurava. A cor e o caimento deixam a produção muito adulta e refinada.",
  ],
  "saia-chiffon-fluida": [
    "As camadas de chiffon criam um movimento lindo, mas não aumentam o quadril. Ficou leve e muito feminina.",
    "Comprei a 38 e o cós se ajustou sem apertar depois do almoço. O elástico é confortável e não enrola.",
    "Usei a off-white num casamento durante o dia e o forro deu cobertura certinha. Não precisei colocar nada por baixo.",
    "A terracota tem uma cor viva e elegante, perfeita para combinar com tons neutros. Pessoalmente é ainda mais bonita.",
    "Tenho 1,58 m e usei com sandália de plataforma. O comprimento midi ficou delicado e não achatou a silhueta.",
    "Ela balança de um jeito maravilhoso quando a gente anda. Fiz fotos ao ar livre e o resultado ficou muito romântico.",
    "Gostei bastante da saia e da qualidade do forro. Só achei o cós um pouco firme no primeiro uso, depois assentou bem.",
    "Coloquei com camiseta e tênis e não ficou formal demais. É realmente uma peça que dá para usar em ocasiões bem diferentes.",
    "A preta é fluida sem ser transparente e não arma. Virou minha solução para sair arrumada nos dias quentes.",
    "A numeração correspondeu às medidas informadas; peguei 42 e caiu perfeitamente no quadril. Compra online sem surpresa.",
  ],
  "saia-renda-romantique": [
    "A renda tem um desenho floral muito delicado e não pinica na pele. O forro nude realça cada detalhe de um jeito lindo.",
    "Usei no civil com uma camisa de seda e ficou exatamente como eu imaginava: romântico, elegante e sem exagero.",
    "O cós é bem estruturado e deixa a cintura desenhada. A saia não gira nem sai do lugar enquanto caminho.",
    "Peguei a 40 seguindo as medidas do quadril e serviu certinho. O zíper invisível fecha com facilidade e fica bem discreto.",
    "De perto dá para ver o capricho da renda e da barra. Nenhuma pontinha desfiada, veio tudo impecável.",
    "A transparência aparece só onde deve e o forro oferece segurança. Fiquei confortável até em ambiente bem iluminado.",
    "Combinei com uma blusa simples e a saia fez toda a produção. É uma peça especial sem ser difícil de usar novamente.",
    "Tenho cintura fina e quadril largo, então normalmente preciso ajustar. Nessa modelagem a proporção ficou ótima de primeira.",
    "Amei o resultado, embora o comprimento tenha ficado um pouco maior em mim. Com salto médio resolveu e o caimento ficou elegante.",
    "Foi uma compra para aniversário de casamento e valeu muito. Meu marido também reparou nos detalhes da renda.",
  ],
  "conjunto-espresso-alfaiataria": [
    "O conjunto chegou e já montei três looks diferentes. Colete e calça funcionam lindamente juntos e também separados.",
    "A calça wide leg alongou muito minhas pernas e não marcou o quadril. O tom espresso deixa tudo mais sofisticado.",
    "Usei numa reunião importante e me senti segura e bem-vestida o dia todo. A alfaiataria não perde a forma quando sento.",
    "O cinto acompanha o conjunto de verdade e arremata bem a cintura. Não parece um brinde colocado só para completar.",
    "Tenho 1,73 m e fiquei feliz porque a calça teve comprimento suficiente para usar com salto. Isso quase nunca acontece comigo.",
    "O colete transpassado veste bem no busto e não fica abrindo. Escolhi o M pela tabela e o ajuste foi preciso.",
    "A cor marrom escura é muito chique e combina com creme, preto e dourado. Já usei cada peça de um jeito diferente.",
    "O tecido tem bom peso, cai reto e não amassa à toa. Viajei com o conjunto na mala e ele chegou praticamente pronto para vestir.",
    "Sou mais baixa e fiz apenas a barra da calça, o restante ficou perfeito. A cintura não sobrou nas costas.",
    "Fazia tempo que eu procurava um conjunto feminino sem cara de uniforme. Esse tem presença e continua muito confortável.",
  ],
  "conjunto-rose": [
    "O rosé é suave e elegante, nada infantil. Usei em um chá de bebê e a cor ficou linda nas fotos ao ar livre.",
    "A saia tem movimento e o colete marca a cintura sem apertar. Juntos deixam a silhueta muito equilibrada.",
    "Gostei da possibilidade de repetir as peças separadas. O colete com jeans ficou moderno e a saia com camisa ficou romântica.",
    "Escolhi o G por causa do busto e o fechamento assentou bem, sem abrir entre os botões. A tabela me orientou direitinho.",
    "Fui madrinha no civil e queria algo delicado que não fosse vestido. O conjunto ficou apropriado e diferente na medida certa.",
    "O tecido da saia não gruda nas pernas e acompanha o passo com leveza. Passei a tarde toda confortável.",
    "Pessoalmente o tom é um rosé queimado bem sofisticado. Com sandália nude e pérola ficou uma produção linda.",
    "Tenho 1,60 m e precisei ajustar só um pouquinho a barra. A cintura e o quadril serviram sem nenhuma alteração.",
    "Veio bem embalado e com o colete mantendo a estrutura. O acabamento das duas peças está muito bem feito.",
    "Recebi tantos elogios que já combinei de emprestar para minha irmã. É delicado, mas tem bastante personalidade.",
  ],
  "vestido-aurora-rose": [
    "O laço removível é uma ótima ideia: usei com ele no jantar e sem ele no escritório. Parecem duas blusas diferentes.",
    "O brilho do tecido é suave e fica elegante mesmo durante o dia. A cor rosé iluminou muito meu rosto.",
    "As mangas têm volume bonito sem deixar os ombros enormes. O punho mantém tudo no lugar e dá um acabamento charmoso.",
    "Coloquei por dentro de uma calça de alfaiataria e ela não criou excesso de tecido na cintura. O caimento é bem leve.",
    "Tenho braços mais cheinhos e o G ficou confortável, inclusive no punho. Não senti apertar em nenhum momento.",
    "A gola continua alinhada depois de horas de uso e o laço não fica escorregando. Dá para perceber cuidado na modelagem.",
    "Usei com jeans e salto para um jantar e ficou arrumada sem esforço. Já virou minha blusa favorita para sair.",
    "O rosé corresponde às fotos e não puxa para laranja. Achei um tom feminino e muito fácil de combinar.",
    "Chegou sem fio puxado e com os botões bem presos. Pelo tecido delicado, gostei bastante do capricho na embalagem.",
    "No corpo ela fica fluida e não cola nas costas. É confortável até em dia quente, apesar das mangas compridas.",
  ],
  "calca-alfaiataria-off-white": [
    "A off-white tem forro e não ficou transparente nem sob luz forte. Finalmente uma calça clara que posso usar sem preocupação.",
    "Peguei a 40 pela medida do quadril e a cintura não ficou sobrando. A modelagem assentou muito bem atrás.",
    "As pregas dão espaço para sentar sem repuxar e ainda deixam a frente alinhada. Usei no trabalho por horas com conforto.",
    "Tenho 1,75 m e o comprimento funcionou com salto baixo. A perna reta cria uma linha muito elegante.",
    "O cinto no mesmo tom elevou bastante o conjunto. Também testei com cinto marrom e a calça ganhou outra proposta.",
    "O tecido é encorpado, porém não esquenta demais. Não marcou bolso, lingerie nem as pequenas dobrinhas da cintura.",
    "Sou baixinha e fiz a barra, como já esperava. Fora isso, a 36 vestiu tão bem que não precisei mexer em mais nada.",
    "Combinei com camisa azul para uma reunião e depois com regata no fim de semana. É muito mais versátil do que imaginei.",
    "Depois de um dia inteiro sentando e levantando, os joelhos não ficaram deformados. A alfaiataria mantém um visual bonito.",
    "A cor é clara na medida, sem parecer branco hospitalar. Ficou sofisticada com tons de areia e acessórios dourados.",
  ],
};
